export const TINYMCE_REL_OPTIONS = [
    { title: 'None', value: 'noopener' },
    { title: 'Alternate', value: 'alternate' },
    { title: 'Author', value: 'author' },
    { title: 'Bookmark', value: 'bookmark' },
    { title: 'Canonical', value: 'canonical' },
    { title: 'DNS Prefetch', value: 'dns-prefetch' },
    { title: 'External', value: 'external' },
    { title: 'Expect', value: 'expect' },
    { title: 'Help', value: 'help' },
    { title: 'Icon', value: 'icon' },
    { title: 'License', value: 'license' },
    { title: 'Manifest', value: 'manifest' },
    { title: 'Me', value: 'me' },
    { title: 'Module Preload', value: 'modulepreload' },
    { title: 'Next', value: 'next' },
    { title: 'No Follow', value: 'nofollow' },
    { title: 'No Referrer', value: 'noreferrer' },
    { title: 'Opener', value: 'opener' },
    { title: 'Pingback', value: 'pingback' },
    { title: 'Preconnect', value: 'preconnect' },
    { title: 'Prefetch', value: 'prefetch' },
    { title: 'Preload', value: 'preload' },
    { title: 'Prerender', value: 'prerender' },
    { title: 'Prev', value: 'prev' },
    { title: 'Privacy Policy', value: 'privacy-policy' },
    { title: 'Search', value: 'search' },
    { title: 'Stylesheet', value: 'stylesheet' },
    { title: 'Tag', value: 'tag' },
    { title: 'Terms of Service', value: 'terms-of-service' },
  ];